print("Hello world!")
print("Anusha", 123,"manju", sep= ' @@')
print("Anusha", 123,"manju", sep= ' 22')
print("Anusha", 123,"manju", sep= ' *' ,end= "   ")
print("hellow")
print("Anusha", 123,"manju", sep= ' *' )
print("hellow")